<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ir.jetvam</groupId>
        <artifactId>jetvam-backend</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>jetvam-business-modules</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>identity</module>
        <module>product</module>
        <module>origination</module>
        <module>assessment</module>
        <module>guarantee</module>
        <module>contract</module>
        <module>payment</module>
        <module>facility</module>
        <module>merchant</module>
        <module>transaction</module>
        <module>settlement</module>
        <module>notification</module>
    </modules>
</project>
