create table i18n_message
(
    id           bigint generated by default as identity primary key,
    message_key  varchar(255)             not null,
    locale       varchar(35)              not null,
    message_text text                     not null,
    description  varchar(500),
    active       boolean                  not null default true,
    version      bigint                   not null default 0,
    created_at   timestamp with time zone not null default current_timestamp,
    updated_at   timestamp with time zone not null default current_timestamp,
    constraint ck_i18n_message_key_not_blank check (btrim(message_key) <> ''),
    constraint ck_i18n_locale_not_blank check (btrim(locale) <> ''),
    constraint ck_i18n_message_text_not_blank check (btrim(message_text) <> '')
);

create unique index uk_i18n_message_key_locale
    on i18n_message (message_key, lower(locale));

create index ix_i18n_message_locale_active
    on i18n_message (lower(locale), active);

comment on table i18n_message is 'Localized messages consumed by Jetvam message source';
comment on column i18n_message.locale is 'BCP 47 language tag such as fa, fa-IR or en-US';
